implemented cluster info CRU
sktelecom/tks-info pull request #4
Opened 2021-04-19 08:58 UTC by jabbukka

* cluster 정보를 생성, 업데이트, 조회 할 수 있는 gRPC API 구현
* in-memory에 cluster정보를 저장

2021-04-20 01:14 UTC, zugwan requested changes

2021-04-20 01:14 UTC, zugwan commented on pkg/info/cluster/accessor.go
> +	if _, exists := c.clusters[newClusterID]; exists {
uuid.New()가 생성하는 값이 겹치는 경우가 많을 거 같진 않은데, 고유한 값이 나올 때까지 재시도 하는게 바람직하지 않을까요? (혹은 횟수를 제한해서라도) 사용자가 입력한 값이 아닌 서비스 내부에서 생성하는 값의 충돌로 인한 에러가 사용자에게 전파되는 것이 맞는 지 잘 모르겠습니다.

2021-04-20 01:28 UTC, jabbukka commented on pkg/info/cluster/accessor.go
> +	if _, exists := c.clusters[newClusterID]; exists {
사실 충돌하는 경우는 일어나기 힘들겠지만, 내부에서 여러번 리트라이를 할 수 있을 것 같습니다. 리트라이 횟수는 10번으로 fix해도 될것같은데 10번동안 충돌하면 뭔가 진짜 이슈가 있다고 판단해도 될것같아서요.

2021-04-20 01:38 UTC, jabbukka commented on pkg/info/cluster/accessor.go
> +	if _, exists := c.clusters[newClusterID]; exists {
retry 하도록 코드 반영하였습니다.

2021-04-20 02:18 UTC, zugwan approved these changes
LGTM

2021-04-21 04:57 UTC, seungkyua approved these changes

2021-04-21 04:57 UTC, merged